version: '3'

services:
  #Setup Node

  server:
    build: ./server
    expose:
      - ${APP_SERVER_PORT}
    environment:
      API_HOST: ${API_HOST}
      PP_SERVER_PORT: ${APP_SERVER_PORT}
    volumes:
      - ./server:/server
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    command: npm run dev
  #Setup Client
  client:
    build: ./client
    environment:
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose:
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes:
      - ./client/src:/client/src
      - ./client/public:/client/public
    links:
      - server
    command: npm start
