# You should always specify a full version here to ensure all of your developers
# are running the same version of Node.
FROM node:8

# Override the base log level (info).
ENV NPM_CONFIG_LOGLEVEL warn

WORKDIR /server

# Install all dependencies of the current project.
COPY package.json package.json
COPY npm-shrinkwrap.json npm-shrinkwrap.json
RUN npm install

# Copy all local files into the image.
COPY . .

# Build for production.
CMD ["npm","run","dev"]
EXPOSE 4000
